language: generic
sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_2a7ed9759856_key -iv $encrypted_2a7ed9759856_iv -in .github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key

script:
- .scripts/travis_update.sh
